title: Decision Intelligence Conference Deadlines
description: Countdowns to top conference deadlines
author: Inteligensi

domain: "konferen.si"
baseurl: ""

#twitter_hashtag: machinelearning
github_username: inteligensi
github_repo: Deadlines

markdown: kramdown
ga_id:

include: ['_pages']
