title: Decision Intelligence Conference Deadlines
description: Countdowns to top conference deadlines
author: Abhishek Das

domain: "https://inteligensi.github.io/Deadlines/"
baseurl: "Deadlines"

#twitter_hashtag: machinelearning
github_username: inteligensi
github_repo: TanggalKonferensi

markdown: kramdown
ga_id:

include: ['_pages']
